### ISSUE TITLE
Group Duplicate Users

### ISSUE THREAD

**Issue by catherinemarvin** [Flotype/now#109]
Adding a user to a group who is already in a group results in strange behavior.

**Comment by steveWang** [comment]
What qualifies as strange behavior? Also, if you're using the version on npm, I'd like to imagine that it was solved by commit c83a303aacb91183176951274ff313ca11132517.

**Comment by catherinemarvin** [comment]
We're seeing many copies of the same person in a group. 

For bug testing purposes, we have a button that adds a user to a special group, but if the same user clicks on the button multiple times, he is added to the group multiple times. At least, the group.count shows up as more than one.

**Comment by steveWang** [comment]
I apologize if I was a bit indirect earlier. What I meant by my previous post was, "Try out the version on github and see if that fixes your problem." Unless, of course, you were already using that version, in which case you should try out v0.7 :D.

Edit: I think I might have been misunderstanding your problem. Do you mean "adding a user to a group that he's already in", or "adding a user to a group when he's already in a different group"? If it's the latter, I'm surprised adding users to groups works at all, since `everyone` itself is a group internally.

**Comment by catherinemarvin** [comment]
My mistake for being not completely clear. I was referring to adding a user to a group that he was already in. I'm using the npm version of now [edit: multitasking is hard and typos appear everywhere], but if updating the version will fix our issues, I'm willing to give it a shot.

**Comment by steveWang** [comment]
By npm version of node, I'll assume you mean Now (yeah, the names are pretty similar). But yes, I do believe that this particular issue will be resolved by updating Now using the version on Github.

**Comment by ericz** [comment]
This is fixed in 0.7
