### ISSUE TITLE
Socket.IO Namespace

### ISSUE THREAD

**Issue by jafstar** [Flotype/now#149]
I'm trying to use now.js with Apache and have a node.js page setup such as:

http://mysite.com/node

Where '/node' is where I'm using node.js

I'm able to attach the nowjs/now.js file by doing:

src="/node/nowjs/now.js"

in the header's "script" tags

and I can even attach : src="/node/socket.io/socket.io.js"

and they're getting 200 OK responses.

But now.js still wants to attach it's own version of Socket.IO and it keeps looking for it at:

http://localhost:8080/socket.io/socket.io.js

I've been trying to use .htaccess to reroute it, but it doesn't seem to work.

Is there  a way to set options on socketio during it's initialization to utilize it's namespaces such as:

io.of('/node').on('connection', function (sockets) { });

Any suggestions?

**Comment by steveWang** [comment]
I think what you want to configure is NowJS itself: 

```
nowjs.initialize(server, {host: 'mysite.com', port: 80});
```

**Comment by ericz** [comment]
On the client side you can try specifying the url to connect to explicitly:

`window.now = nowInitialize('http://mysite.com/node');`

When using this method, make sure to use the version of the now.js client lib in github rather than the one served at /nowjs/now.js so that auto connection does not occur.

**Comment by jafstar** [comment]
thanks for your help.
