### ISSUE TITLE
Simple somegroup.count

### ISSUE THREAD

**Issue by andrecaribe** [Flotype/now#176]
Simple `everyone.count` or `somegroup.count` to get the number of users at the time dont exist anymore?
I need to limit the number of users in a room. Which path should I follow?

**Comment by ericz** [comment]
Hi andrecaribe,

`somegroup.count` should still exist? What is the issue you are experiencing?

**Comment by ericz** [comment]
```
 everyone.count(function(count){
      console.log(count);
 });
```

Note that .count is now an asynchronous function

**Comment by andrecaribe** [comment]
@ericz, you write here https://github.com/Flotype/now/issues/49#issuecomment-1002217

I would like to access the value in a synchronous manner. Any way, I could do what he wanted, with more work, but it was done. Thanks!

**Comment by steveWang** [comment]
You can technically access it in a synchronous manner; it just won't be compatible with the cluster version, since there's really no way to access a group's count synchronously without blocking when users are potentially spread across multiple servers. Try `Object.keys(group.users).length`. Not advised.

**Comment by ericz** [comment]
@andrecaribe steveWang's method will work if you need synchronous access but is not documented.

Good luck!
Eric
