### ISSUE TITLE
now.js transferred as 'text/plain'?

### ISSUE THREAD

**Issue by leiwan5** [Flotype/now#18]
I'm using firefox 4.0rc2. A warning "Resource interpreted as Script but transferred with MIME type text/plain." triggered when loading now.js.

**Comment by leiwan5** [comment]
sorry, it's chrome 10, not firefox

**Comment by sridatta** [comment]
Thanks for letting us know. It's added to the list of bugs to fix.

**Comment by dvv** [comment]
Frankly, there should be an option to relay serving static files to an external app (nginx?) or a middleware layer -- to say, to the code which is capable of setting etags,cache-control and so on.

For setting **SERVER** and **PORT** is in essense the same as the rendering a template, right?

**Comment by ericz** [comment]
now.js content-type  'text/plain' has been changed to  'text/javascript'

This issue is now fixed.

@dvv, we set **SERVER** and **PORT** on first request of now.js, then we cache it since it will never change in the lifetime of the service instance. 
If you prefer to serve it statically using nginx etc. , simply download **http://localhost:port/socket.io/socket.io.js** and **http://localhost:port/nowjs/now.js**. Since that now.js will have the server and port already filled out, you can serve that static file without issue.

**Comment by dvv** [comment]
This still leaves unnecessary checks for certain URLs ('/nowjs/now.js') in request handlers in setups like mine where dynamic handlers stand before static ones. I mostly meant elimination of these checks. The same in socket-io itself about checking whether url is /socket.io/socket.io.js which is not switchable out and just eats ticks...
