### ISSUE TITLE
/socket.io/socket.io.js not found on other computers when using express

### ISSUE THREAD

**Issue by adrusi** [Flotype/now#22]
I made a simple demo in express and it worked fine in two different web browsers on the same computer, but when I tested on another computer in the same network, it didn't work and the console said something about socket.io.js being undefined.

**Comment by ericz** [comment]
Hi Adrusi,

I believe this issue is this:

When you start you example application, and then run now.js for the first time, it caches the server location depending on the address you are trying to access it from.

For example,

If you the first time, you access with `http://localhost:myport/` then it will load socket.io.js from `http://localhost:myport/socket.io/socket.io.js`. Subsequently, if you try to access from a different computer in the network, you will still be loading it from `http://localhost:myport/socket.io/socket.io.js`, which is obviously no longer valid.

The fix is to access it from `http://ip:myport/` instead of from `http://localhost:myport/` or `http://127.0.0.1:myport/`, as then every subsequent access will load `http://ip:myport/socket.io/socket.io.js` instead of trying to get it from localhost

**Comment by ericz** [comment]
Closing
