### ISSUE TITLE
Now.js client-side disconnect with Flash open file dialog

### ISSUE THREAD

**Issue by tommedema** [Flotype/now#56]
This bug may be related to Flash.

When a client is connected to the server, it will disconnect when opening a Flash based file browser / file open dialog for more than about 5 seconds. This does not happen with a HTML5 file browser, only with the flash file browser.

This bug occurs every time to me on Chrome 10.0.648.133 (77742) with Ubuntu 10.10.

**Comment by ericz** [comment]
I think his is caused by the open file dialog blocking flash network operations, which causes the server to think the client has timed out and thus disconnected. 

This is indeed an issue that can't be fixed, however in the reconnection support that we will be implementing, we'll be able to remedies the issue by reconnecting the client upon disconnection and subsequent reconnection. This should be a seamless process.

**Comment by tommedema** [comment]
That'd be great. So the disconnect event will not be fired if it can reconnect?

The question is whether it can even reconnect when a file dialog is open.

**Comment by ericz** [comment]
The disconnect event will likely be fired. There may be a different event if
reconnect fails.

The reconnect cannot happen while the dialog is open, it will likely have to
be after the dialog is closed. I am not sure if that is the case, but if the
server disconnects while dialog is open then it probably can't reconnect
while dialog is open is my guess.

Eric

On Mon, Apr 18, 2011 at 2:55 PM, tommedema <
reply@reply.github.com>wrote:

> That'd be great. So the disconnect event will not be fired if it can
> reconnect?
> 
> The question is whether it can even reconnect when a file dialog is open.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Flotype/now/issues/56#comment_1023749

## 

510-691-3951
EECS Student at UC Berkeley
http://ericzhang.com
