### ISSUE TITLE
name undefined on connect

### ISSUE THREAD

**Issue by johnou** [Flotype/now#63]
I've put together a small test application which produces the undefined output, perhaps I am not taking the right approach?

**Comment by johnou** [comment]
And here I was thinking I could attach a file after I submitted the issue :) I will send it to the team mailing list.

**Comment by dvv** [comment]
Or you could create a public gist instead ;)

**Comment by johnou** [comment]
Here you go! https://gist.github.com/938746

**Comment by ericz** [comment]
Due to browser limitations, new variables values have a slight delay. This means the first time you set `now.name` there will be a < 1 second lag time before it gets synced to the server, this is purely a browser limitation. However subsequent changes to the variable will be real time.

There is no promise that `.connected` on the server is called after specific variables have been set on the client, instead the best practice is for the client to call a server function when the client has finished settings its variables.
