### ISSUE TITLE
No unit testing?

### ISSUE THREAD

**Issue by balupton** [Flotype/now#70]
Hey guys,

Was just about to file a bug for now.js and provide some unit tests to test against it, and discovered you aren't using any (or at least not in the repo...)

Would you guys like me to add some?

I use unit testing extensively in [History.js](https://github.com/balupton/history.js). With it I fire the tests up in the list of supported browsers and they run through all the tests and lets me know what's broken and what's not :)

**Comment by ericz** [comment]
Yes we need to do unit testing for sure. This is one of those things that we haven't been able to do due to being spread thin, but it's def on the list!

**Comment by sridatta** [comment]
Seconded! Docs for the codebase and unit tests are what we desperately need.

**Comment by balupton** [comment]
Just tried a few unit testing frameworks (vows, nodeunit, and expresso) for my own stuff. Vows was extremely buggy, for nodeunit I didn't like it's syntax, and expresso worked great.

**Comment by ericz** [comment]
We made some integration tests here: https://github.com/ericz/now-tests

The repo is kind of out of date but we run them against every push. Because of the cross-network nature of Now we found it hard to write unit tests of substance so we created the integration test suite instead, using the Jasmine framework.
