### ISSUE TITLE
More Code Comments

### ISSUE THREAD

**Issue by balupton** [Flotype/now#72]
Hey guys,

Went for a lookaround in the Now.js codebase, and there is about 20 comments in the full ~1500 lines of code...

Which definitely has put me off making any pull requests to the now.js code base... as I would have to spend a good day or two understanding the code.

Are there any plans to make the now.js codebase more contributor friendly?

**Comment by ericz** [comment]
Yes we do plan on making the codebase better documented. We're also planning on making many other style and efficiency optimizations in the code. Unfortunately we are strapped for time because we're prioritizing an unannounced product. However, we are hiring for this summer so when things settle down around June, we'll be able to improve our focus on the codebase.

**Comment by ghost** [comment]
Hi guys! Good to hear, Eric. Let us know if we can do anything to help.

**Comment by ericz** [comment]
Thanks guys! I've started writing more code for the libs. 

We're also planning on revamping documentation this week along with even more code comments.
