### ISSUE TITLE
Return value vs. callback

### ISSUE THREAD

**Issue by clyfe** [Flotype/now#79]
Any news on this discussion?

http://news.ycombinator.com/item?id=2316079

```
Rival node.js RPC project (dnode) author chiming in here.
This is pretty neat and I like the emphasis on getting stuff going in as few lines as possible but I'm not convinced that return values and                          
implicit result callbacks are the way to go for asynchronous requests, which is how I understand this project to work. Often when you 
want to make a remote call you'll be doing some I/O on the server side, which in node is asynchronous so you can't return right away.     
Passing along a callback from the client side works much better when the I/O actions have some values to call the client back with.
```

**Comment by ericz** [comment]
Hi clyfe, The comment is no longer relevant as we have eliminated "implicit result callbacks" and thus return values since v0.3

Additionally we have since added many additional features that puts NowJS in a difference space compared to dnode. Specifically NowJS is aiming to be a comprehensive tool for building real time web applications, including features such as groups (aka channels, rooms) whereas dnode focuses on the RPC aspect.

**Comment by clyfe** [comment]
Thanks for the reply.

PS
1. A section titled "Why Now.js" would be helpful to build momentum.
2. I think a good idea would be to enable the GH wiki.
3. Why no release tags?
